/**
 * api → store normalization layer.
 *
 * The WASM client (`@slyng/client`) is generated by tsify, which emits every
 * Rust `Option<T>` / `#[serde(default)]` field as `T | undefined`. The store
 * view-models (`ServerData`, `ChannelData`, `MessageData`, …) are stricter:
 * they require those fields, or type them `string | null`, and a couple carry
 * `[key: string]: unknown` index signatures that structurally reject the
 * generated interfaces outright.
 *
 * Rather than widen the view-models (which cascades: a widened field then
 * breaks every downstream consumer that expected the narrow type), we
 * normalize once, here, at the boundary where API data enters the stores.
 * Each function:
 *   - defaults every drifted optional to the view-model's expected value,
 *   - returns a fresh object literal, which satisfies the index-signature
 *     view-models that a named generated type cannot be assigned to,
 *   - is idempotent, so re-normalizing an already-normalized value (e.g. the
 *     `[...older, ...current]` pagination merge) is a no-op.
 *
 * Pure and dependency-free at runtime (all imports are type-only), so this
 * module is unit-testable without loading Svelte runes or the WASM client.
 */

import type {
	Server,
	Channel,
	ChannelCategory,
	ServerRole,
	ServerMember,
	Message,
	DmChannelSummary,
	UserResolveResult
} from '@slyng/client';
import type { ServerData, ChannelData, CategoryData } from './servers.svelte';
import type { RoleData } from './roles.svelte';
import type { MemberData } from './members.svelte';
import type { MessageData } from './messages.svelte';

/** Default message type when the wire payload omits it. Matches the Rust
 *  `MessageType` default; a real message always carries one at runtime. */
const DEFAULT_MESSAGE_TYPE = 'text';
/** Empty permission bitmask (no permissions granted). */
const EMPTY_PERMISSIONS = '0';

export function normalizeServer(s: Server): ServerData {
	return { ...s, member_count: s.member_count ?? 0 };
}

export function normalizeChannel(c: Channel): ChannelData {
	return { ...c, position: c.position ?? 0 };
}

export function normalizeCategory(c: ChannelCategory): CategoryData {
	return { ...c, position: c.position ?? 0 };
}

export function normalizeRole(r: ServerRole): RoleData {
	return {
		...r,
		color: r.color ?? null,
		position: r.position ?? 0,
		permissions: r.permissions ?? EMPTY_PERMISSIONS
	};
}

export function normalizeMember(m: ServerMember): MemberData {
	// The fresh spread is what makes this assignable to MemberData: its
	// `[key: string]: unknown` index signature rejects the named `ServerMember`
	// type directly but accepts an object literal.
	return { ...m };
}

export function normalizeMessage(m: Message | MessageData): MessageData {
	return { ...m, type: m.type ?? DEFAULT_MESSAGE_TYPE };
}

/** A DM channel row as the DM list/ignored views consume it: presence flags
 *  resolved to concrete booleans, the counterpart id to `string | null`. */
export interface DmChannelView {
	id: string;
	type: string;
	last_message_at?: string;
	other_user_id: string | null;
	other_user_instance_url?: string | null;
	is_blocked: boolean;
	is_ignored: boolean;
}

export function normalizeDmChannel(c: DmChannelSummary): DmChannelView {
	return {
		...c,
		other_user_id: c.other_user_id ?? null,
		is_blocked: c.is_blocked ?? false,
		is_ignored: c.is_ignored ?? false
	};
}

/** A resolved-recipient lookup with the home instance narrowed to
 *  `string | null` (the DM compose/request views branch on `registered`). */
export interface ResolvedUser {
	did: string;
	syr_instance_url: string | null;
	registered: boolean;
}

export function normalizeResolvedUser(u: UserResolveResult): ResolvedUser {
	return {
		did: u.did,
		syr_instance_url: u.syr_instance_url ?? null,
		registered: u.registered
	};
}
